CORCI-1103 Build: Add CentOS 8.4 and Leap 15.3
daos-stack/openpa pull request #13
Opened 2021-08-17 19:52 UTC by JohnMalmberg

Signed-off-by: John E Malmberg <john.e.malmberg@intel.com>

2021-08-24 20:50 UTC, jolivier23 requested changes

2021-08-24 20:50 UTC, jolivier23 commented on packaging/Dockerfile.centos.7
> +# Copyright 2018-2020, Intel Corporation
2020?

2021-08-24 20:50 UTC, jolivier23 commented on packaging/Dockerfile.mockbuild
> +# Copyright 2018-2020, Intel Corporation
2020?

2021-08-27 18:12 UTC, JohnMalmberg commented on packaging/Dockerfile.centos.7
> +# Copyright 2018-2020, Intel Corporation
I do not think that one has changed since 2020.   This is copied from the packaging repo, so would not be changed here.

2021-08-27 18:13 UTC, JohnMalmberg commented on packaging/Dockerfile.mockbuild
> +# Copyright 2018-2020, Intel Corporation
Needs to be fixed in the packaging repo, and then all the of these repos need to be updated.

2022-03-08 18:41 UTC, JohnMalmberg commented
Obsolete

2022-03-08 18:41 UTC, closed without merging